on:
  push:
    branch:
      - develop

name: Test and deploy on develop environment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Setup Gradle 7.6.1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Setup Gradle 7.6.1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          MY_GITHUB_ACTOR: ${{ secrets.MY_GITHUB_ACTOR }}

  sonarqube:
    name: sonarqube
    uses: ./.github/workflows/test-quality.yaml
    secrets:
      githubToken: ${{ secrets.MY_GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      sonarHostUrl: ${{ secrets.SONAR_HOST_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: TODO
        run: echo todo

