name: Test quality

on:
  workflow_call:
    secrets:
      sonarToken:
        required: true
      githubToken:
        required: true
      sonarHostUrl:
        required: true

jobs:
  test:
    name: GradleTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Setup Gradle 7.6.1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      # Run unit test
      - name: Test
        run: ./gradlew test

      - name: Test Success
        if: success()
        run : echo "All tests passed."

      - name: Test Fail
        if: failure()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const pull_number = "${{github.event.number}}"
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "There is something wrong with test codes.",
             event: "REQUEST_CHANGES"
            })

      # Run sonarqube test and check dependency vulnerability
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Check code and check dependency vulnerability
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          SONAR_TOKEN: ${{ secrets.sonarToken }}
          SONAR_HOST_URL: ${{ secrets.sonarHostUrl }}
        run: |
          ./gradlew build sonarqube --info
